### ISSUE TITLE
How to train a model with a new dataset?

### ISSUE THREAD

**Issue by liusongxiang** [MadryLab/robustness_applications#2]
Hi! Very interesting work!
Could you please provide some guidance of how to train a new model with my own dataset?
Tx!

**Comment by andrewilyas** [comment]
Hi! You may be interested in the ``robustness`` library that we released, which allows you to do exactly this and has detailed documentation and tutorials. All the notebooks here are actually based on this library.

Code: https://github.com/MadryLab/robustness
Docs: https://robustness.readthedocs.io
