### ISSUE TITLE
Regd. paper "Image Synthesis with a Single (Robust) Classifier" 

### ISSUE THREAD

**Issue by abhishekaich27** [MadryLab/robustness_applications#4]
How are you getting the generated images from your network? Is it the penultimate layer of the classifier network? If yes, isn't that a vector for the classifier layer?

Pardon me for the naivety.

**Comment by dtsip** [comment]
We are treating the images as input variables and we are using them to maximize class scores. See our blog post for more details: http://gradientscience.org/robust_apps/ .
